### ISSUE TITLE
[Feature Request] Create `haskell-graphql` tag on Stackoverflow

### ISSUE THREAD

**Issue by sunwukonga** [haskell-graphql/graphql-api#138]
I would do this myself, but I have insufficient reputation. A reputation of 1500 is required to open a [new tag](https://stackoverflow.com/help/privileges/create-tags).

Once this tag is up I can do a PR on the README to direct questions to that tag on SOF.

**Comment by jml** [comment]
I also lack the reputation.

**Comment by rschmukler** [comment]
I have [created the tag](https://stackoverflow.com/questions/tagged/haskell-graphql). Cheers!

**Comment by rschmukler** [comment]
If anyone wants to write up formal usage guidance I can also associate that with the tag.

**Comment by jml** [comment]
Thanks @rschmukler. I've submitted usage guidance (but I don't really have a sense of whether it's appropriate or not).
