### ISSUE TITLE
Custom Scalar Types?

### ISSUE THREAD

**Issue by russmatney** [haskell-graphql/graphql-api#162]
Is it possible/in the roadmap to allow users to implement custom scalars? Looking specifically to add a UUID scalar, but it feels like that should be possible from the app layer.

It looks possible to do custom validation via an input object type, but that'd essentially require parsing the text to a UUID twice, (once to validate, the second time to use it).

**Comment by jml** [comment]
I think this is what #151 is aiming at. Definitely in the roadmap (although bear in mind nobody is paid to work on this).

**Comment by russmatney** [comment]
Gotcha. Just wanted to be sure this functionality wasn't already available somewhere. Thanks much for the effort, it is much appreciated!
