### ISSUE TITLE
Hydrating a GraphQL Object with a parent GraphQL Object vs API call?

### ISSUE THREAD

**Issue by EdmundsEcho** [haskell-graphql/graphql-api#189]
The conceptual question is: What is the best way to hydrate the query tree  while allowing the end-user to sub-select various branches "along the way" given:  
-  several 1:N parent-child node relationships
- the scope of the unique IDs for each child node, is the parent

Here is the intended query: 
```
{    
   records ( id:"xxx" ) {
        id   -- uid
        measurements ( type:"xx" ) {
            type   -- uid
            components ( names: (Maybe (List Text) ) {   << Resolver in question
                                  compName   -- uid
                                  compValues
         }
   }
}
```
This following is a Field that will be added to my list of Root queries:

```
-- Root Field for Components
type CompsRoot =
  Argument "parent"     (**TBD**)  :>
  Argument "names"      (Maybe (List Text)) :>
  Field    "components" (List Component)
```
What should I use as a **parent** (given the parent needs to be a single Measurement)

  - Option 1: API.Measurements + MeaKey = Components (I'm hosting the data in `Data.Map`)
     - task: find a way to reference the `MeaKey`, perhaps using the GQL Measurement Object? <P>

  - Option 2: GQL.Measurement Object has a `Field "components" (List Components)`
     -  how would my resolver filter `(List Components)` using the `Field "compName" Text`?
     -  *should I be using a parent GQL Object to hydrate a child Object?*<P>

By definition of this question, I'm clearly missing something in how I'm thinking about this.  Any guidance would be greatly appreciated.

\- E

**Comment by jml** [comment]
Hi,

I'm afraid there's a lot I don't understand about this question.

A few suggestions:
* provide context on what you are trying to achieve
* provide a self-contained, reproducible example (see http://sscce.org/)

Leaving this open in case others have insight.

jml

**Comment by EdmundsEcho** [comment]
I appreciate your comments.  I'm close to figuring it out.  When I do, I will present the solution.  Admittedly, I was incorrect in how I was thinking about it.
