### ISSUE TITLE
Pointers for how to implement HasAnnotatedInputType for records with more than 3 fields

### ISSUE THREAD

**Issue by EdmundsEcho** [haskell-graphql/graphql-api#197]
I've been working through the definition of `toValue` with the help of a couple of links posted in another issue related to `FromValue`.  However, by definition of the volume of code, I feel as though I'm missing something.  Is there anyone that might be able to suggest a way to implement `HasAnnotatedInputTYpe` for the following data type?

```
data MixItemInput = MixItemInput
  { nameKey    :: Maybe Text
  , nameKeys   :: Maybe [Text]  
  , textValues :: Maybe [Text] 
  , intValues  :: Maybe [Int32]
  , spanValues :: Maybe [SpanInputType]  -- an instance of HasAnnotedInputType
  } deriving (Show, Generic)
```

__Update__
The need to implement this has been made moot with the recent fix in deriving the instance generically (... now with more than 3 records).

\- E

**Comment by dminuoso** [comment]
Fixed by https://github.com/haskell-graphql/graphql-api/pull/195/commits/5747b8896955ca0d092a203318be22f7b8a4c48c
