### ISSUE TITLE
Latest release points to 0.1.1 (not 0.3.0)

### ISSUE THREAD

**Issue by declension** [haskell-graphql/graphql-api#216]
### Steps to replicate
Go to [the graphql-api releases](https://github.com/haskell-graphql/graphql-api/releases) page.

### Expected
Latest release pointer is at the newest release (currently`0.3.0`)

### Actual
It points to `0.1.1` (over two years old now):
![image](https://user-images.githubusercontent.com/3322808/53497065-41cff380-3a9b-11e9-9a89-f06de43cb416.png)

**Comment by teh** [comment]
Thanks for flagging! I created a release from the v0.3.0 tag just now.
